import type { Metadata } from "next";
import { Alatsi, Lexend_Deca } from "next/font/google";
import "./globals.css";
import QueryWrapper from "@/providers/queryWrapper";
import { ConfirmationDialogProvider } from "@/providers/ConfirmationDialogProvider";
import { ModalProvider } from "@/providers/modal-context";
import { Toaster } from "sonner";
import { Modal } from "@/components/modal/modal";
import ScrollProgress from "@/components/scroll-progress";
import { Suspense } from "react";

const primary = Alatsi({
  subsets: ["latin"],
  variable: "--font-primary",
  weight: ["400"],
});

const secondary = Lexend_Deca({
  subsets: ["latin"],
  variable: "--font-secondary",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${primary.variable} ${secondary.variable}`}>
        <QueryWrapper>
          <ConfirmationDialogProvider>
            <ModalProvider>
              <Toaster
                richColors
                duration={3000}
                position="top-right"
                className="toast-sonner-position"
                closeButton={true}
                style={{ zIndex: 1000000 }}
              />
              {children}
              <Suspense fallback={<></>}>
                <ScrollProgress />
              </Suspense>
              <Modal />
            </ModalProvider>
          </ConfirmationDialogProvider>
        </QueryWrapper>
      </body>
    </html>
  );
}
